# HyperFleet Standard golangci-lint Configuration
# Reference: https://golangci-lint.run/usage/configuration
#
# This is the baseline configuration for all HyperFleet Go repositories.
# See standards/linting.md for full documentation of this standard.
#
# golangci-lint should be installed and versioned via bingo in each repository.

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
      - name: unexported-return
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

  unused:
    check-exported: false

  unparam:
    check-exported: false

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

linters:
  enable:
    # Code Quality
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - unconvert
    - unparam
    - goconst
    - exhaustive

    # Code Style
    - misspell
    - lll
    - revive
    - gocritic

    # Security
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

issues:
  # Add repository-specific generated code directories here
  exclude-dirs:
    - pkg/api/openapi
    - data/generated

  exclude-rules:
    # Relaxed rules for test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
